### PR TITLE
Change latitude and longitude to CharField

### PR DESCRIPTION
**Pull request by sidharthv96**
Integer fields cannot store Latitude and Longitude

### CODE REVIEW

**Comment by sidharthv96** [comment]
Also, please consider changing latt to latitude. As this is a REST endpoint which is supposed to be made open for others, it would be better to have standardized naming.

**Comment by sidharthv96** [comment]
#102

**Comment by sidharthv96** [comment]
I usually use charfield too. But did not wan't to change the datatype to string as they might be integrating this in an App. So I gave the accuracy to 10 decimal points. So no rounding will happen unless you give more than 10 decimal points. Usually coordinates don't go over 5 or 6 points.

**Comment by ragsagar** [comment]
What is the issue when they integrate this in the app? Even if you are using `DecimalField` you might need to send this data as string explicitly, otherwise on app side the value might get rounded.

**Comment by ragsagar** [comment]
what about the migration for these changes? They are planning to create it once the models are ready?

**Comment by sidharthv96** [comment]
I think migrations are better created inside the server and not provided by devs.

**Comment by ragsagar** [comment]
Created inside the server? Migrations are supposed to be generated with the model code at some point and added to version control.

**Pull request closed without merging**
