### PR TITLE
Added Payments Gateways, changed Federal Bank status, added Amazon li…

### LINKED ISSUE #402: QR code to display in https://keralarescue.in/reg_contrib/
### Subject of the issue
CM relief fund redirection (https://donation.cmdrf.kerala.gov.in/) loading too slow and hence recommended to display the QR codes directly in this page,  https://keralarescue.in/reg_contrib/ for easy transfer

### PR DESCRIPTION
**Pull request by aravindharinair**
### Issue Reference
This PR addresses the Issue : Fixes #402 #90 #36 #52 
This PR references Pull Request: #468 by @arjunkomath and adds his changes.
This PR references Pull Request #510 by myself and provides single squashed commit for better readability.

### Summarize

@arjunkomath has added payment links for all payment methods as per [CM's Disaster Relief Fund](https://donation.cmdrf.kerala.gov.in/)

@jilvin has restructured layout to be neater.

I have edited to reflect Federal Bank's temporary outage and the addition of HDFC Bank to possible payment methods.

Also added Amazon's [Kerala Needs Your Help](https://www.amazon.in/b?ie=UTF8&node=8891257031&pf_rd_p=2c1c1ac8-3c7f-4880-b5a7-e870ec58eefa&pf_rd_r=TEX7HJ9QSHSJQE3EX59W) reference link for material contributions.

> Verify bank details and payment methods
> Test on various devices

### CODE REVIEW

**Comment by aravindharinair** [comment]
@riginoommen @vigneshhari @vrthra @arjunkomath
Could you test it if it's working as expected? And verify bank details?

**Comment by saji89** [comment]
Guys we need to push this through fast. People may prefer UPI as mode of donation, as that's more easier..

**Comment by jilvin** [comment]
@biswaz @vigneshhari It's sad to see important prs not being merged on time. Kills the spirit of contributing. This pr has been ready for at least 16 hours. Cheers.

**Comment by riginoommen** [comment]
@biswas can you please merge this its more than 24 hours

**Comment by riginoommen** [comment]
@biswaz

**Comment by arjunkomath** [comment]
@biswaz FYI. PR is ready for merge.

**Comment by aravindharinair** [comment]
Any updates regarding this PR?

**Comment by riginoommen** [comment]
@syam3526 Can you please do merge this. we should value the effort of the contribution. this is more important

**Comment by jilvin** [comment]
@aravindharinair The core team is busy working with the core functionality of the platform. They are working real hard to deliver the core functionalities on time. That's why this is getting delayed.

**Comment by aravindharinair** [comment]
@jilvin Yup, Understood that by looking at the Slack chat. No hurries for this. 😄

**Comment by biswaz** [comment]
Officials want just a link to the official portal. Sorry KSITM requirements are our first priority. I know exactly what it feels like be on the contributor side. Been there, done that.

**Pull request closed without merging**
