### PR TITLE
Added GPS location and automatic location detection along with accuracy

### PR DESCRIPTION
**Pull request by irshadshalu**
This PR adds automatic **GPS location fetching** for devices with GPS support and stores it in the database.

Also added is a "**Open in maps**" button for **request list** which directly opens the location in google maps 

model fields added -

- **latlng** - GPS location as comma seperated field
- **latlng_accuracy** -  accuracy of the GPS location.

view edited -

- Added **latlng** and **latlng_accuracy** to forms

html changes -

- Set GPS fields as readonly.
- Fetch GPS location using javascript.

### CODE REVIEW

**Comment by joicemjoseph** [comment]
it seems working. better to display accurate place name instead of latlong

**Comment by irshadshalu** [comment]
Can be easily done using `http://maps.googleapis.com/maps/api/geocode/json?latlng=8.5581139,76.8814559&sensor=false` . But not sure if there is a daily API limit (As google maps APIs went rigorous with pricing

**Comment by irshadshalu** [comment]
No. I still can access the  URL:
http://maps.googleapis.com/maps/api/geocode/json?latlng=8.5581139,76.8814559&sensor=false

And get the correct response, but not when running from localhost. 

So it is probably domain based and not client IP or Cookie based.

**Comment by sadu** [comment]
GoogleMaps JS APIs no longer work without a key, we would need one to call their geo-coding APIs. 
ref: https://developers.google.com/maps/documentation/geocoding/intro#ReverseGeocoding

**Comment by irshadshalu** [comment]
Added this using [Nominatim](https://wiki.openstreetmap.org/wiki/Nominatim) API which uses OpenStreetMap, 

Seems to be working fine, do check the new commit.

**Comment by biswaz** [comment]
Require testing before merge @vigneshhari

**Comment by irshadshalu** [comment]
Are you trying from mobile or desktop?

I have removed the timeout and maximumAge in #89 . Do merge that as well, otherwise Accurate GPS will not be fetched before timeout.

**Pull request merged**
