### PR TITLE
make GPS field editable

### LINKED ISSUE #125: URGENT fix needed - unable edit location info
**SEVERITY : HIGHEST SEVERITY AND PRIORITY**

**Issue:** Unable to manually edit the location information. I was trying to enter information of someone's parents and not able to edit.

Environment: Firefox on mac os  and Chrome : both tested on macos.

image

image

Steps to reproduce:

**scenario 1:**

1. Allow browser to Access GPU location
2. The location details are auto filled

3. Unable to edit to the location

This is the case in Chrome and FF

**Scenario2:** 

1. Don't allow browser to access location
2. The location details are hidden

image

PS: Power went out and I will not be to confirm.

### PR DESCRIPTION
**Pull request by kracekumar**
### Summary

- Fix #125.
- Add missing migration file.
Note: .gitignore ignores migrations directory, which app should track all migration files unless admin would like to generate migration file in the production server.

### CODE REVIEW

**Comment by vrthra** [comment]
@kracekumar When one clicks "Requesting for others", and submits the request, the GPS field is no longer saved in the request. (If you go to the requests page, you can see that no GPS is filled in that request)

**Comment by vrthra** [comment]
@kracekumar once you have fixed it, could you please ping me on slack? (@rahul)

**Comment by kracekumar** [comment]
@vrthra Fixed. I don't know the slack group.

**Comment by vrthra** [comment]
@kracekumar I will test and update.

**Comment by biswaz** [comment]
@kracekumar see readme

**Comment by vrthra** [comment]
Tested the three scenarios:
1) Allow location, but submit as for others
2) Disallow location, submit own
3) Disallow location, submit as others

Works.

**Comment by irshadshalu** [comment]
Testing should be done in the /requests/ page as well.

**Pull request merged**
