### PR TITLE
Validate phones numbers to 10 digits

### LINKED ISSUE #191: Phone number validation is still broken
Phone numbers of length less than 10 is being accepted.

The front end validation ensures that the text box accepts only digits 0-9 (as well as + - and . )
The phone field in the models have max_length = 10, so it addresses the concern of the upper limit.

The problem can be fixed by adding a RegexValidator on the phone.CharField. The regex can be ^[0-9]{10}$

I've tried this and it works. However, in the case of the request page, when regex validation fails on the backend, the "Allow Location - നിങ്ങളുടെ സ്ഥലം കൊടുക്കുക" help modal pops up again (because the user is redirected back to the request page itself). It can be extremely confusing to the user. 

Thoughts, anyone?

### PR DESCRIPTION
**Pull request by salmanulfarzy**
Fix length of mobile number to 10 digits starting with (6,7,8,9) and and remaining could be any digit. This would be enforced only during submit and strangely `max_length` was not forced before submit. 

#### Prevents the following issue (Taken from production website)

invalid moblie number

Fix #191

### CODE REVIEW

**Comment by Neonkraft** [comment]
As I already pointed out in #191  , this will work BUT it will cause a lot of confusion on the Request for Help page.

Steps:
1. Fill all the details in the Request for Help except the phone number. Make the phone number less than 10 digits long.
2. Submit the form
3. The validator will reject the entry, and redirect back to the page. The "Allow Location - നിങ്ങളുടെ സ്ഥലം കൊടുക്കുക" modal will pop up again(since it shows up on window.load), making the user think that it's the location that's missing.

**Comment by abdullatheef** [comment]
Looks good for me.

**Comment by salmanulfarzy** [comment]
Thank @Neonkraft for pointing that out and excuse me for overlooking the thread, Made the patch few hours ago and just submitted it. Will try to find alternative methods in the meantime.

**Comment by Neonkraft** [comment]
@salmanulfarzy that's fine. I guess we'll leave the call to the admins.

**Comment by asimqt** [comment]
Can we try JS validation instead?

**Comment by Gotham13121997** [comment]
I have added verification using js. It prevents alphabets or negatives from being entered in the field itself. But one must never rely on frontend verification

**Comment by salmanulfarzy** [comment]
@Gotham13121997 is implementing front end validation on #207

**Comment by salmanulfarzy** [comment]
Merged with #581

**Pull request closed without merging**
