### PR TITLE
Adding instructions to setup Docker environment in the README.md

### LINKED ISSUE #439: Dev Improvement: Instructions for setting up Docker environment for development/testing
### Subject of the issue
People who use docker may find it easy to setup the dev/test environment in Docker, instead of installing multiple software on their machines.

### Steps to reproduce
Not an issue, but an improvement

### Expected behaviour
Instructions are added to setup the Docker environment

### PR DESCRIPTION
**Pull request by dipukp**
### Issue Reference
This PR addresses the Issue : Fixes #439 

### Summarize
Added instructions in README.md to setup a docker environment for dev/test 
- no fucntionality/code changes present as part of this PR.

### CODE REVIEW

**Comment by jose2007kj** [comment]
trying to test

**Comment by jose2007kj** [comment]
could't test as i am a beginner to docker

**Comment by karthikpanicker** [comment]
Startup of web container container failed with the following log.

web_1  |   File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
web_1  |   File "<frozen importlib._bootstrap_external>", line 728, in exec_module
web_1  |   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
web_1  |   File "/code/floodrelief/settings.py", line 115, in <module>
web_1  |     "LOCATION": env('REDIS_URL'),
web_1  |   File "/usr/local/lib/python3.7/site-packages/environ/environ.py", line 123, in __call__
web_1  |     return self.get_value(var, cast=cast, default=default, parse_default=parse_default)
web_1  |   File "/usr/local/lib/python3.7/site-packages/environ/environ.py", line 277, in get_value
web_1  |     raise ImproperlyConfigured(error_msg)
web_1  | django.core.exceptions.ImproperlyConfigured: Set the REDIS_URL environment variable
db_1   | 2018-08-17 19:49:13.294 UTC [69] LOG:  incomplete startup packet
rescue-kerala_web_1 exited with code 1
Aborting on container exit...
Stopping rescue-kerala_web_1 ... done
Stopping rescue-kerala_db_1  ... done

**Comment by r3dsm0k3** [comment]
@karthikpanicker please test #445  instead of this. #445 makes this one obsolete.

**Comment by dipukp** [comment]
THis is closed as #445 makes this one obsolete

**Pull request closed without merging**
