### PR TITLE
Sndp487/sms responder

### LINKED ISSUE #767: [Feature Request] - SMS Integration to gather consent from volunteers
### Subject of the issue
SMS to be sent to all volunteers. SMS contents
1. Acknowledge the help with volunteer name.
2. Unique Shortened URL to seek an opinion from volunteer to find his current status.

URL should be unique and should direct to a poll page to indicate the status of the volunteer. The status may be tagged as Active /Inactive. The poll may work in such a way that once a volunteer clicks the link, he is registered as an active volunteer in the system.

### Your environment
REST API offered by KSITM for SMS Gateway.

### PR DESCRIPTION
**Pull request by sndp487**
### Issue Reference
This PR addresses the Issue : Fixes #767 

### Summarize
Script to send SMS for volunteer consent.

### CODE REVIEW

**Comment by biswaz** [comment]
We used a redis queue for sending sms earlier
https://github.com/IEEEKeralaSection/rescuekerala/pull/578

**Comment by Gotham13121997** [comment]
try python-dateutil instead of dateutil in requirements.txt

**Comment by biswaz** [comment]
fixed in #804

**Comment by biswaz** [comment]
This is an independent script, written in python2

**Comment by biswaz** [comment]
@sndp487 add instructions for usage. like: csv should only contain rows with is_active = True

**Pull request merged**
