### PR TITLE
Frontend performance improvements

### LINKED ISSUE #216: Extract bootstrap styles used to different file and use vanilla JS.
We're loading the whole Bootstrap and jQuery. We could extract these styles to a different file as we don't need every style coming with BS. Similarly we could use jqLite or vanilla JS instead of whole jQuery.

### PR DESCRIPTION
**Pull request by amits97**
### Issue Reference
This PR addresses the Issue : Fixes #216 

### Summarize
- I combined the GOK, IEEE and IT mission images into a sprite for now: so that only one image would be needed to load. Saving us to use just one network call of `~11KB` instead of 3 network calls adding up to 14KB.
- Moved JQuery and Bootstrap CDN urls to `cdnjs.com`
- DNS prefetch `cdnjs.cloudflare.com`
- Added tag to prerender `/request`

### CODE REVIEW

**Comment by prakashsanker** [comment]
You might want to use `preload` here instead of `prerender` in order to push assets early.

**Comment by amits97** [comment]
@prakashsanker `prerender` preemptively loads all of the assets of a certain URL. Isn't that what is desirable? `preload` should be specified individually for each asset.

**Comment by jjtmanalel** [comment]
Where i can see the steps to do testing

**Comment by amits97** [comment]
- Follow the steps here first https://github.com/IEEEKeralaSection/rescuekerala#testing-pull-requests
- Make sure that the images are loading fine - ie, the logos at the top. That is where majority of the change is. You can compare this by loading another tab with the current live site.
- Check "Network" tab in Chrome developer tools and make sure jQuery and Bootstrap files are getting downloaded correctly.
- Basic functionality / flows of existing site shouldn't be broken. I did all this from my side and found no issues. But it is good to have another pair of eyes :)

**Comment by malgamves** [comment]
Testing!

**Comment by amits97** [comment]
@malgamves Hey, I checked now also, it is working properly. Looks like the CSS file is cached. Could you try in incognito mode once? If still seeing problem, can you try clearing the `staticfiles` directory and run this command?

`python3 manage.py collectstatic`

**Comment by amits97** [comment]
Should look exactly like the current home page. Here is a screenshot from my machine

screen shot 2018-08-18 at 10 31 00 am

**Comment by salmanulfarzy** [comment]
Improved load time, But alignment issue on mobile. 

### Load

#### master

default logo 

#### PR 
 sprite logo


### Mobile View

#### master

mobile-default-logo 

#### PR 

mobile-sprite-logo

**Comment by amits97** [comment]
@salmanulfarzy can you check now? I have pushed the mobile style fixes

**Comment by sengar23** [comment]
I have further optimized the site size by writing custom css and js, removing unwanted bootstrap code, both in css and js. Also optimized the images.

Optimized frontend site
image

Current site
image

**Comment by amits97** [comment]
@sengar23 Good work! But I think the icons were a good visual aid to quickly select an option.

**Pull request closed without merging**
