### PR TITLE
Rebase #130 - Added camp facility details page

### PR DESCRIPTION
**Pull request by jaseemkm**
This is a duplicate of #130. I had to pull in the changes committed in #130 and rebase it with master as the original author wasn't responding.

- Includes a section for listing the Rescue camp locations.
- Only admin can add a new Rescue camp.

### CODE REVIEW

**Comment by vrthra** [comment]
@jaseemkm Could you please add some details as to how to populate the rescue camps? Not able to figure out how to reproduce the issue.

**Comment by vrthra** [comment]
Oh ok; any idea how to set the admin user and password so I can login to my test instance?

**Comment by jaseemkm** [comment]
@vrthra, if you haven't created the super user already for your test instance, run this command and you will be prompted to set the username and password for the admin user.
`python3 manage.py createsuperuser`.
Once it's successful, login to /admin and go the Rescue camp detailss list.

**Comment by ajnas** [comment]
We're implementing this in a better way for issue #161. Let's not merge till it's ready.

**Comment by sanpra1989** [comment]
[](url)
screenshot from 2018-08-16 12-28-21
@jaseemkm

**Comment by vrthra** [comment]
@ajnas can you point me to the other PR for #161 ? The issue is labeled urgent, so want to get a start on testing it.

**Comment by vrthra** [comment]
In the dash board, the "Rescue camp detailss" has an extra 's' :) Could you please fix it?

Marking this as tested since the particular functionality seems to work fine, but as @ajnas mentions, they may have a better implementation so wait for merging until we hear back.

**Comment by sanpra1989** [comment]
The error was due to an issue on my side. No issue spotted other than "detailss"

**Comment by vrthra** [comment]
Marking this back to "Tested".

**Pull request merged**
