### PR TITLE
Updated phone field to check for valid phone numbers. Requestee phone can be empty.

### LINKED ISSUE #495: Remove Phone number from Mandatory field, as there are several people whose phones are dead.
Remove Phone number from Mandatory field, as there are several people whose phones are dead.
Encountered this problem while data entry, as there are several people who needs rescue whose phone batteries are dead. 
I suggest to remove phone number from Mandatory field and add option to provide reason for not entering the phone number.

### PR DESCRIPTION
**Pull request by ssat335**
### Issue Reference
This PR addresses the Issue : Fixes #495  #491 
Stores international number
Max length 15
Uses established library
Updates all phone fields, except for requestee as they may be stressed and may not worry about numbers.

### Please, describe what the PR does, the changes you have made.
Updated the phone field to an established library based on https://github.com/stefanfoulis/django-phonenumber-field.
Accepts now phone numbers in format +911234567890. Does internal checking on its validity.
Removed number check
Added the installed application in requirements.txt
Added the installed application to INSTALLED_APPS

### You will be required to do 
pip install django-phonenumber-field
python3 manage.py makemigrations
python3 manage.py migrate
python3 manage.py runserver

### CODE REVIEW

**Comment by riginoommen** [comment]
@ssat335 Changes are Ok (y). Please fix the Conflicts

**Comment by ssat335** [comment]
Will do in 4 hrs time.

**Comment by kunalgrover05** [comment]
I think in your form clean methods, you can allow both standard format and in case it is a 10 digit number, it can prepend '+91' to it before passing it to the model.

**Comment by ferricfury** [comment]
std codes for including in regex.. source (https://kerala.gov.in/std-codes)

4864\|4734\|4894\|4922\|477\|4891\|4893\|470\|496\|4890\|495\|497\|4899\|484\|480\|4897\|4895\|4936\|4997\|4828\|476\|4994\|4896\|4898\|4923\|481\|4885\|4935\|483\|4924\|479\|4892\|4865\|485\|4728\|4868\|4931\|4822\|491\|468\|4985\|4869\|4933\|475\|474\|4735\|478\|4926\|4982\|490\|471\|4862\|494\|469\|487\|4998\|4884\|4829\|

**Comment by salmanulfarzy** [comment]
@ferricfury See #657 with added support for STD landline numbers.

**Comment by ssat335** [comment]
stale pull request, hence closing

**Pull request closed without merging**
