### PR TITLE
Add missing migration file and make GPS field editable

### LINKED ISSUE #125: URGENT fix needed - unable edit location info
**SEVERITY : HIGHEST SEVERITY AND PRIORITY**

**Issue:** Unable to manually edit the location information. I was trying to enter information of someone's parents and not able to edit.

Environment: Firefox on mac os  and Chrome : both tested on macos.

image

image

Steps to reproduce:

**scenario 1:**

1. Allow browser to Access GPU location
2. The location details are auto filled

3. Unable to edit to the location

This is the case in Chrome and FF

**Scenario2:** 

1. Don't allow browser to access location
2. The location details are hidden

image

PS: Power went out and I will not be to confirm.

### PR DESCRIPTION
**Pull request by kracekumar**
### Summary

- Fix #125.
- Add missing migration file. 

Note: .gitignore ignores migrations directory, which app should track all migration files unless admin would like to generate migration file in the production server.

### CODE REVIEW

**Comment by biswaz** [comment]
Will merge manually

**Comment by biswaz** [comment]
Because it requires rebase

**Comment by kracekumar** [comment]
Thank you @biswaz

**Comment by biswaz** [comment]
@kracekumar Please rebase and resubmit. 
The new js toggle hides the fields. Fix that too

**Comment by kracekumar** [comment]
@biswaz Sure. Let me look into it.

**Comment by vrthra** [comment]
#135 seems a duplicate of this PR

**Comment by kracekumar** [comment]
@biswaz Have fixed the issue. Please take a look.

**Comment by biswaz** [comment]
Can you submit a new PR, Im afraid the migration will break something

**Comment by kracekumar** [comment]
You mean, I should remove the migration file?

**Comment by biswaz** [comment]
yes

**Comment by kracekumar** [comment]
Done

**Pull request closed without merging**
