### PR TITLE
implemented Pagination

### PR DESCRIPTION
**Pull request by vigneshhari**

### CODE REVIEW

**Comment by sidharthv96** [comment]
Hi, do you think this https://datatables.net/examples/basic_init/alt_pagination.html will be more user friendly.
Also the end users will be having low network connectivity, so server side pagination will require multiple requests to the server and will also increase the server load.
Client side pagination will be faster and all the data can be transferred in a single request right?

**Comment by JijinJayakumar** [comment]
@sidharthv96 
I hope https://datatables.net/examples/server_side/simple.html 
this will be more effective,
already implemented normal paginations in PR 7-15 
just update the Py code and change the dtable.js 
` "processing": true,
        "serverSide": true,
        "ajax": "url"`
 file in the static/s folder

**Comment by vigneshhari** [comment]
The server is currently hosted at Heroku free account and it can't process all added requests at all times for client-side pagination, so till we move to a better server we are trying to cut the load to the server

**Comment by sidharthv96** [comment]
I was actually asking about complete client side vs server side pagination.
Saw in news that many mobile towers are getting shut down and all, So if the entire data is transferred in a single request, wont that be easier to use from the client's perspective, instead of sending one request for each page.

I had actually faced similar issue in a project and hence shared.

If a user wants to go to page 5, it means 5 separate requests and more load to server, moreover, It means that the user might have to wait 10sec between pages if the network is poor. We can cache the db results to reduce the load on the DB.
https://docs.djangoproject.com/en/2.1/topics/cache/

Single request fetching more data is usually favored.
https://softwareengineering.stackexchange.com/questions/179931/multiple-database-accesses-or-one-massive-access

Please keep this in mind after the new server is set up.
Thanks

**Comment by ajaykanayil** [comment]
Please add page numbers rather than "prev - next" buttons... and add button classes to links for better usability...

**Comment by vigneshhari** [comment]
@sidharthv96 I'll update the cache and will setup client-side pagination once the server is shifted,
@ajaykanayil I'll add that now

**Comment by vigneshhari** [comment]
@ajaykanayil I've Updated the pagination

**Pull request merged**
