### PR TITLE
Update map.js

### LINKED ISSUE #390: Location not opening in new tab.
Please check URL: https://keralarescue.in/map/#
screen shot 2018-08-17 at 8 06 15 pm

Anyone already working maps. Please do the required changes in JS file.
https://github.com/IEEEKeralaSection/rescuekerala/blob/master/static/js/map.js

### PR DESCRIPTION
**Pull request by gauravsaini**
Fix to open url  links in new tab

### Issue Reference
This PR addresses the Issue : Fixes #390 

### Summarize
Added target attribute to be target="_blank" so that it opens up in new window

> Since file is minfied look for maps.google.com and then you will find the relevant change.

### CODE REVIEW

**Comment by pranavashok** [comment]
Testing this.

**Comment by pranavashok** [comment]
Tested on FF, Chrome and also through the 'Device Mode'. Works fine.

@gauravsaini  I also discovered another issue which could possibily be fixed in this same PR as its minor and also deals with map.js. The "Request" button at the top-right corner has an absolute URL to keralafloods.in/request. This needs to be relative so that we are actually redirected to the /request page on the local env. Do you think you could fix this?

**Comment by gauravsaini** [comment]
@pranavashok Will track in separate PR. Tried to locate it but didnt find it in short time.

**Comment by pranavashok** [comment]
Thanks, its at position 284352.

**Comment by gauravsaini** [comment]
@pranavashok Done

**Comment by pranavashok** [comment]
Reviewed the last commit.

**Comment by gauravsaini** [comment]
Declining this since this is now part of map.js

**Pull request closed without merging**
