### PR TITLE
Added Support chat option on home page

### PR DESCRIPTION
**Pull request by nabilnalakath**
I have added a script for integrating a volunteer chat option. Right now we are providing chat support on a different domain with the help of many active volunteers from the slack group.  The same script is used here also to provide chat support to the visitors of this site also. Testing is required before merging.

**Please test load time and network performance as well.** 

The working functionality can be seen here:- http://keralarescuesupport.com/

Eg Image:-

image

### CODE REVIEW

**Comment by jose2007kj** [comment]
whatsapp image 2018-08-17 at 8 23 46 pm
UI working fine in mobile

**Comment by jose2007kj** [comment]
whatsapp image 2018-08-17 at 8 23 33 pm
Home page view

**Comment by jose2007kj** [comment]
screenshot from 2018-08-17 20-32-26
Desktop view ...... Ui is ifne

**Comment by jose2007kj** [comment]
screenshot from 2018-08-17 20-32-26
Its fine

**Comment by salmanulfarzy** [comment]
Layout tested and looks good on iOS(Firefox) and Linux(Firefox). 

Considering page load, Throttled to **Regular 3G**. Chat is loaded only after initial page render, So shouldn't be affecting initial performance. But, considering network and device performance, Wouldn't this be better on different domain with back link from here ?

|              	| Data (KB) 	| Requests 	| `DOM` load (s) 	| Non blocking load time (s 	| Total time (s) 	|
|:------------:	|:---------:	|:--------:	|:--------------:	|:------------:	|:--------------:	|
| Without Chat 	|    ~220   	|     9    	|      ~2.01     	|     ~3.29    	|      ~4.0      	|
| With Chat    	|    ~526   	|    20    	|      ~2.25     	|    ~10.25    	|     ~13.26     	|

**Comment by abhilal007** [comment]
Code is working on both crome and firefox and also responsive enough to work on mobile.

**Comment by abhilal007** [comment]
please change the label to tested

**Comment by nabilnalakath** [comment]
@salmanulfarzy  It is already running on the different domain - http://keralarescuesupport.com. I was also concerned about the load to the main site. But I got many requests to add it to this page and hence made the pull request.

**Comment by salmanulfarzy** [comment]
Work on http://keralarescuesupport.com is awesome, Notably the resource map, I'm asking everyone to use both the domains to fetch help. But on http://keralarescue.in/ users device might be running on fumes, Then this additional load and rendering could be an issue to complete the request.

**Comment by naveenpf** [comment]
Please dont merge this

**Comment by salmanulfarzy** [comment]
Can we have a link to http://keralarescuesupport.com from home page ?

**Pull request closed without merging**
