### PR TITLE
Malayalam Transliteration of district names

### PR DESCRIPTION
**Pull request by aslamues**
Added malayalam transliteration of district names to the script.

### CODE REVIEW

**Comment by asimqt** [comment]
Looks good.

**Comment by vigneshhari** [comment]
Please update the models file also, its located in main app/models.py

**Comment by shajith** [comment]
There's two other PRs also addressing this issue: 

https://github.com/IEEEKeralaSection/rescuekerala/pull/136
https://github.com/IEEEKeralaSection/rescuekerala/pull/142

Could we consolidate on one of those fixes?

**Comment by vrthra** [comment]
Since this has already been handled, closing this PR.

**Pull request closed without merging**
