### PR TITLE
Unit Tests for models

### PR DESCRIPTION
**Pull request by Kavit900**
### Issue Reference
This PR addresses the Issue : Fixes #

### Summarize
Please, describe what the PR does, the changes you have made.

-> This PR basically contains unit tests for our models.

### CODE REVIEW

**Comment by Kavit900** [comment]
Can someone review this and get it merged, it's just the tests.

**Comment by ja8zyjits** [comment]
Similar to #562

**Comment by Kavit900** [comment]
Can we merge this @ja8zyjits ?

**Comment by biswaz** [comment]
@Kavit900 Sorry for the delay. We couldn't look into your contributions due to other urgencies. We've recently added tests from @ja8zyjits. Could you please improve upon them, after rebasing.

**Comment by Kavit900** [comment]
@biswaz  no worries, let me push another PR after rebasing master from scratch. Thanks a lot guys :)

**Pull request closed without merging**
