### PR TITLE
Update home.html

### PR DESCRIPTION
**Pull request by Amalkarunakaran**
### Issue Reference
This PR addresses the Issue : Fixes #

### Summarize
Please, describe what the PR does, the changes you have made.

> Also, mention the key points if any to look into while code reviews

### CODE REVIEW

**Comment by biswaz** [comment]
Can't see visible changes on some of the highlighted words in the diff.

**Comment by vigneshhari** [comment]
@biswaz "Abhyarthikkan" spelling has changed

**Comment by biswaz** [comment]
Yes, but what about the other words. May be some unicode stuff

**Comment by Amalkarunakaran** [comment]
There was some unicode issues with some malayalam word when we try to edit..so i corrected that one.

**Pull request merged**
