### PR TITLE
Added Mahe as a District.

### LINKED ISSUE #270: Add Mahe as a district
### Subject of the issue
I am guessing Mahe is also affected.

### PR DESCRIPTION
**Pull request by theryecatcher**
### Issue Reference
This PR addresses the Issue : Fixes #270 

### Summarize
Please, describe what the PR does, the changes you have made.
Added Mahe in models.py.

> Also, mention the key points if any to look into while code reviews

### CODE REVIEW

**Comment by baijum** [comment]
My understanding is that we need to run this command and commit the auto-generated migrations script.
```
python manage.py makemigrations
```

**Comment by theryecatcher** [comment]
Ok on it.

**Comment by shajith** [comment]
dupe of https://github.com/IEEEKeralaSection/rescuekerala/pull/277 ?

**Comment by sks** [comment]
The approval was not on purpose. Apologies. Was a bug on github mobile

**Comment by labtocat** [comment]
@theryecatcher Can you please remove the migration file. It can cause conflict and break the server

**Comment by theryecatcher** [comment]
Sorry I thought we had to add the migrations file.
Done.

**Comment by theryecatcher** [comment]
Sorry thought we are supposed to add the migrations file too.
Done.

**Comment by vrthra** [comment]
Dmodash needs translation too. Also, please rebase and resolve the conflict.

**Pull request closed without merging**
