### PR TITLE
Fixing PR 590: Making phone number compulsory for NGO registration..

### PR DESCRIPTION
**Pull request by anuragagrawal0430**
### Issue Reference
This PR addresses the Issue : [PR 590](https://github.com/IEEEKeralaSection/rescuekerala/issues/590)

### Summarize
Phone number in NGO/Company registration was not compulsory. As it is the bare minimum to contact so making it mandatory.

### CODE REVIEW

**Comment by AlexMathew** [comment]
@anuragagrawal0430 Can you include the migrations as well please?

**Comment by AlexMathew** [comment]
Also a duplicate of #570

**Comment by anuragagrawal0430** [comment]
I'm using docker image to run the project. What should I do to create migrations?

**Comment by ragsagar** [comment]
@AlexMathew I don't think this change to `blank` require migration.

**Comment by ja8zyjits** [comment]
any updates? migration fixes?

**Comment by ragsagar** [comment]
Looks like the added migration file has nothing to do with the model changes in this PR.

**Pull request closed without merging**
