### PR TITLE
Fixes #309: Create indexes on request table

### LINKED ISSUE #309: DB indexing needed
1. we need indexes to optimize the query behind this: https://keralarescue.in/requests/?district=&requestee__icontains=&requestee_phone=&location__icontains= (edited)

2. Hide a certain URL 

3. Pagination

### PR DESCRIPTION
**Pull request by lijoantony**
Currently there are not indexes created for the request table, which
is the main table subject to most of the queries. Adding indexes on
district and requestee_phone fields improves the query performance.

Also adds a migration to add these indexes in production db.

### Issue Reference
This PR addresses the Issue : Fixes #309 

### Summarize
Please, describe what the PR does, the changes you have made.

> Also, mention the key points if any to look into while code reviews

### CODE REVIEW

**Comment by ajnas** [comment]
@lijoantony Will you also add index on name and district fields of person table?

**Comment by sachu92** [comment]
currently testing

**Comment by sachu92** [comment]
@lijoantony 'requestee_name' may also be indexed. I guess queries will be more with requestee_name than requestee_phone.

**Comment by kracekumar** [comment]
This is a single field index, to query two or more fields together, you need use [index_together](https://docs.djangoproject.com/en/2.1/ref/models/options/#index-together). 

index_together can take care of `URL:?q1=foo&q2=bar&q3==somethingelse`. AFAIK, But combination of three field length should be less than 255 characters

**Comment by sachu92** [comment]
@lijoantony :  when i run python manage.py migrate in a branch with your PR, it says

Your models have changes that are not yet reflected in a migration, and so won't be applied.
Run 'manage.py makemigrations' to make new migrations, and then re-run 'manage.py migrate' to apply them.


This can be fixed by doing 'makemigrations' and rerunning 'migrate'. 
But, Im not familiar enough with Django to tell if that is the right way to do it.

**Comment by lijoantony** [comment]
@ajnas @sachu92 Will add those changes.

**Comment by lijoantony** [comment]
@kracekumar I assume index_together builds composite index. If so, it is not very useful in this case as composite indexes are useful when there are combinations of fields which are frequently queried together.

**Comment by kracekumar** [comment]
you're right about composite index @lijoantony . From the issue

> we need indexes to optimize the query behind this: https://keralarescue.in/requests/?district=&requestee__icontains=&requestee_phone=&location__icontains= (edited)

So if this query has to be faster, all three fields should be indexed together. Hope I understood correctly. For individual field, db_index=True is sufficing.

**Comment by lijoantony** [comment]
@sachu92 I will close this PR and will send you another one which fixes the migration issue.

**Comment by lijoantony** [comment]
@kracekumar Not necessarily. Postgres would still execute this query fast by scanning three different indexes. Creating a composite index is useful when we have a certain combination of values which are queried frequently. Else it would be a waste of memory. As name & phone values varies a lot in this case, and the same set of (name, phone, district) values are not frequently searched, composite index wouldn't be that useful. Any way, diving into composite indexes without profiling on production data wouldn't be helpful.

**Comment by sachu92** [comment]
sure. :+1:

**Comment by lijoantony** [comment]
Also #387

**Pull request closed without merging**
