### PR TITLE
NGO registration test

### PR DESCRIPTION
**Pull request by ja8zyjits**
### Issue Reference
This PR addresses the Issue : Fixes #

### Summarize
I have added test for the NGO resgistration
Kindly verify it. If it is ok I shall submit others too in the same format

### CODE REVIEW

**Comment by ja8zyjits** [comment]
this is related to #562

**Comment by Kavit900** [comment]
@syam3526 and @ja8zyjits   can you review this PR as well - https://github.com/IEEEKeralaSection/rescuekerala/pull/483/ . Thanks

**Comment by cvrajeesh** [comment]
@ja8zyjits could you please mark the required fields. TBH I feel about organization shouldn't be required

**Comment by xaneem** [comment]
This PR has changed code for several unrelated parts of the code like `CampRequirementsFilter`. Please keep code refactoring separate as this puts additional load on devs who're working on these features as they get conflicts while rebasing.

**Comment by ja8zyjits** [comment]
@xaneem  those were just `pep8s`  should I remove them? the  logics were not changed

**Comment by xaneem** [comment]
@ja8zyjits It's not about logic. People working with that part of the code will get conflicts - I had to spent a lot of time yesterday while rebasing because of something like this :)

**Comment by ja8zyjits** [comment]
@xaneem so how do we go forward with this?

**Comment by ja8zyjits** [comment]
the more this PR gets delayed the more conflicts arise

**Comment by remedcu** [comment]
I will try to do a rebase for this.

**Comment by ja8zyjits** [comment]
better implementation with less hassle in #782 , closing this PR

**Pull request closed without merging**
