### PR TITLE
[1061] Dynamic Meta Description for Sub Pages

### PR DESCRIPTION
**Pull request by jinojossy93**
### Issue Reference
This PR addresses the Issue : Fixes #

Hard coded sub page description for Important Announcements Page 

### Summarize
Please, describe what the PR does, the changes you have made.

I have added new block in base.html and overrided it in announcement.html.

> Also, mention the key points if any to look into while code reviews

The description I could find for this page is "Important Announcements regarding Kerala Rescue Operations".

Please suggest something better if somebody has a better suggestion.

### CODE REVIEW

**Comment by subins2000** [comment]
@jinojossy93 Can ya modify this to include per announcement description please ? #1054 has been merged which gives a permalink for each announcement. It would be great if title & description of each announcement page is unique so that the link previews in whatsapp/social media stands out.

**Comment by jinojossy93** [comment]
@subins2000 lemme check the latest changes. 
I'll start work on that soon.

**Comment by jino-qb** [comment]
@subins2000 
Completed the requested changes. Please have a look

**Comment by subins2000** [comment]
Tested this. It works good. By having descriptions, the link preview in whatsapp/social media for individual announcements will be better.

@biswaz @vigneshhari @tomahawk-pilot

**Comment by jinojossy93** [comment]
@biswaz @vigneshhari @tomahawk-pilot @subins2000 

I missed to correct the default description for announcement page. Completed the same now.

**Comment by subins2000** [comment]
much better

**Pull request merged**
