### PR TITLE
Added RequestHelp Endpoint

### PR DESCRIPTION
**Pull request by SaifurRahmanMohsin**
### Issue Reference
This PR addresses the Issue : Closes #94, #22 

### Summarize
Lets any mobile client add a request help to the rescuekerala website thro API. The endpoint doesn't need any user authentication as anyone should be able to post a help request, so AllowAny has been used. API documentation [here](https://documenter.getpostman.com/view/182878/RWToQdF1).

### CODE REVIEW

**Comment by WarFox** [comment]
@SaifurRahmanMohsin Please rebase with waster and resolve conflicts

**Comment by kurianbenoy** [comment]
@SaifurRahmanMohsin resolve the conflicting filess

**Comment by SaifurRahmanMohsin** [comment]
Done, as requested.

**Comment by SaifurRahmanMohsin** [comment]
@biswaz Why was this closed. For mo reason?

**Comment by SaifurRahmanMohsin** [comment]
@biswaz Why was this closed?

**Pull request closed without merging**
