### PR TITLE
Added camp facility details page

### PR DESCRIPTION
**Pull request by Devdutt-Shenoi**
I have added a new section to display details of the rescue camp and have taken all measures possible to not break the application. Please Consider this as a response to [Issue #120 ](https://github.com/IEEEKeralaSection/rescuekerala/issues/120)

### CODE REVIEW

**Comment by biswaz** [comment]
please rebase and submit

**Comment by ajnas** [comment]
We're implementing this is a better way for issue #161 . Let's not merge till it's ready.

**Comment by xaneem** [comment]
Please close this. It's already merged in a different PR.

**Comment by salmanulfarzy** [comment]
@riginoommen 

> Please close this. It's already merged in a different PR.
https://github.com/IEEEKeralaSection/rescuekerala/pull/130#issuecomment-413833348

Please close this and remove the labels.

**Pull request closed without merging**
