### PR TITLE
addded slack link to dashboard #759

### PR DESCRIPTION
**Pull request by arpit7714**
### Issue Reference
Added Slack channel link 

### Summarize
Added channel link in the footer

@syam3526 to verify

### CODE REVIEW

**Comment by aravindharinair** [comment]
Addresses issue #759

**Comment by akshayjoyinfo** [comment]
image
is this fine?

@biswaz @syam3526 @arpit7714

**Comment by syam3526** [comment]
dude remove the word developers from it.

**Comment by arpit7714** [comment]
made the chnages @syam3526 , @akshayjoyinfo . please review

**Pull request merged**
