### PR TITLE
Added sharing or copying Button in district wise requirements

### LINKED ISSUE #1089: copy/share option in district wise requirements
### Subject of the issue
No copy/share option in district wise requirements

### PR DESCRIPTION
**Pull request by Gotham13121997**
### Issue Reference
This PR addresses the Issue : Fixes #1089 

### Summarize
Please, describe what the PR does, the changes you have made.

> Adds button to each row of table for copying / sharing. 

Note - Sharing works only with https connection and android devices using chrome (using Navigator.share)

### CODE REVIEW

**Comment by biswaz** [comment]
@sreenadh I think it is for the clipboard copy to work

**Comment by sreenadh** [comment]
@biswaz understood. Showing a alert in catch for Navigator.share would be useful as Navigator.share is available in mobile browsers only.

**Comment by sreenadh** [comment]
Or show copy to clipboard, fb, twitter, email share on big screens and navigator share on small screens. Would require a view page for individual district needs record.

**Comment by sreenadh** [comment]
Add an alert or a flash message saying "copied" in else condition for if(navigator.share) {}. The user doesn't understand what has happened after clicking the share/copy button from a desktop browser.

@Gotham13121997 @biswaz

**Pull request merged**
