### PR TITLE
Fixes issue with table rendering on mobile

### LINKED ISSUE #42: Tables are not showing properly in mobile
Guys, tables not showing properly in mobile - check these pages...

https://keralarescue.in/district_needs/
https://keralarescue.in/requests/

img_9676

### PR DESCRIPTION
**Pull request by nevinvalsaraj**
Fixed issue with columns overlapping without scrollbars.
Fixes #42

### CODE REVIEW

**Comment by nevinvalsaraj** [comment]
Tested with both viewports(mobile and desktop) from Chrome DevTools. Keeps bootstraps responsive features and is scrollable horizontally on mobile with no column overlapping.

**Comment by nevinvalsaraj** [comment]
Updated pull request to re-add `table-responsive` class to district_needs page table that was removed as part of PR #55 which aimed to close Bug #67 by removing the class.

The PR fixes both #67 and #42 by removing manual overwrite of `table-layout` in `style.css` .

**Comment by jilvin** [comment]
@nevinvalsaraj The #42 seems to be fixed. Can you close this?

@biswaz @vigneshhari

**Comment by syam3526** [comment]
cc @IEEEKeralaSection/code-reviewers

**Comment by syam3526** [comment]
cc @IEEEKeralaSection/moderators

**Comment by jilvin** [comment]
Seems this is the recommended way to add responsive tables in Bootstrap 3.

http://bootstrapdocs.com/v3.0.3/docs/css/#tables-responsive

**Pull request closed without merging**
