### PR TITLE
Added Page Titles (Fixing Issue #358)

### LINKED ISSUE #358: Page title need to be displayed.
### Subject of the issue
Page Title is not available for pages like "Registered request","Request for help" etc

### Your environment
* version of your python : NA
* which browser and its version : Chrome
* OS Type (iOS/Android/Linux/Windows) : Android

### Steps to reproduce

1.Go to https://keralarescue.in
2. Click on menu options available in the page.(eg: request for help )
3.Navigate to pages( like request for help,registered requested) and observe the page title.

### Expected behaviour
For each page,page title need to be displayed

### Actual behaviour
Page titles are missing

### PR DESCRIPTION
**Pull request by remedcu**
### Issue Reference
This PR addresses the Issue : Fixes #358 

### Summarize
Added Page Titles

### CODE REVIEW

**Comment by realslimshanky** [comment]
@remedcu this needs to be added to the title meta class as well. It's the important for SEO.

**Comment by dhanrajm** [comment]
@remedcu A suggestion...add malayalam titles as well ?

**Comment by remedcu** [comment]
@dhanrajm I too thought about that, but the heading will be too big then.

**Comment by dhanrajm** [comment]
@remedcu yeah thats right.

**Comment by remedcu** [comment]
@dhanrajm added that as well now, please review :)

**Comment by remedcu** [comment]
All pages have English heading in H1 and Malayalam heading in H2

Please check, test and merge.

**Comment by dhanrajm** [comment]
looks good.
Tested and works

**Pull request merged**
