### PR TITLE
GPS FIelds non editable, solves #225

### LINKED ISSUE #225: Editable GPS Field Causing issues
### Subject of the issue
As warned, making GPS field as editable is causing havoc as many users are entering random URLs/addresses to the location. Refer the screenshot for more information
screenshot_2018-08-17-00-30-58-204_com android chrome
This is caused by  #160 

### Steps to reproduce
Open keralarescue.in/requests/ and submit for a district.. many rows have accuracy and maps link as broken!

### Expected behaviour
Maps co-ordinates should only be comma separated latitude and longitude. 

### Actual behaviour
People can type in anything causing the issue in buttons/display

### Proposed solution
 Revert back to old method of making it read only and only allowing it for self requests (as done in #122 )

### PR DESCRIPTION
**Pull request by irshadshalu**
### Issue Reference
This PR addresses the Issue : Fixes #225 

### Summarize
GPS FIelds are non-editable till we implement some sort of placepicker. More details can be found on #225 

> When testing, also test /requests/ page and Open in Maps button.

### CODE REVIEW

**Comment by biswaz** [comment]
What about limiting to numerical fields

**Comment by biswaz** [comment]
I will add this as a temporary fix

**Comment by irshadshalu** [comment]
Limiting to numerical field/regex will again cause confusion, we can't expect common people to be aware of co-ordinates. This applies to accuracy as well as there is no standard unit for measuring it.

**Comment by irshadshalu** [comment]
Seems like I forgot to set them to readOnly. fixed it on #236

**Pull request merged**
