### PR TITLE
PR for many Old Rebase Required PR's

### PR DESCRIPTION
**Pull request by remedcu**
### Issue Reference
This PR addresses the Issue : Fixes: #15 #196 #548 

### Summarize
All the above PR's mentioned required a rebase and thus I have made all those into a single one. Please check the same and approve it as well as close the other PR's mentioned above.

### CODE REVIEW

**Comment by remedcu** [comment]
For ease of those who are checking:

mainapp/models.py

One Typo corrected and added check for 10 digit mobile verification

mainapp/templates/mainapp/camp_details.html

One Typo corrected

mainapp/views.py

A new line is removed

static/css/style.css

Updated styles to hold columns in screen

templates/home.html

Add Google Maps Relief Resources Page Link: #500

**Comment by jilvin** [comment]
#7 
is a duplicate of #93. The issue is currently discussed at #93.
#15 
All the changes have been merged as of now except in the verbose_name part. Check #15.

**Comment by remedcu** [comment]
As @jilvin told, I have updated the PR to update only select Fixes only.

Please check.

**Comment by remedcu** [comment]
Except for mobile number verification, all the rest are just typo's

Please check @vigneshhari @vrthra @biswaz @shameelsadaka @ashwinrajeev and merge

**Comment by saifali40** [comment]
Tested.

**Pull request merged**
