### PR TITLE
Remove unused variable 'options"

### PR DESCRIPTION
**Pull request by s0md3v**

### CODE REVIEW

**Comment by vkaracic** [comment]
Already removed.

**Comment by s0md3v** [comment]
lmao you could have just closed the PR and said fuck off

**Comment by s0md3v** [comment]
lmao you could have just closed the PR and said fuck off

**Comment by vkaracic** [comment]
I can't close other peoples PR's.

**Comment by s0md3v** [comment]
I know, I opened it about a day ago. They could have just merged it.

**Pull request closed without merging**
