### PR TITLE
Fix messedup pagination links

### PR DESCRIPTION
**Pull request by shanavas786**
### Summarize
Pagination links before
pagination-before

after
pagination-after

### CODE REVIEW

**Comment by shanavas786** [comment]
closes #598

**Comment by akshayjoyinfo** [comment]
Testing 597

**Comment by akshayjoyinfo** [comment]
its not fixed yet

image

**Comment by cvrajeesh** [comment]
tested and looks good to me

**Comment by akshayjoyinfo** [comment]
Working fine

image

last link
image

all  scenarios works fine. (Y)

**Comment by arjun-pp** [comment]
LGTM. Working on both desktop and mobile.

**Pull request merged**
