### PR TITLE
API to mark request as closed

### PR DESCRIPTION
**Pull request by ragsagar**
Add an api to mark request as closed. This can be used by other sites like `keralafights.com` to mark a request as closed.

```
Headers:
Authorization: Token <pregenerated_token>

POST /api/1/requests/<id>/close/
```
Authentication works using DRF's rest authentication. So we need to create an user for `keralafights.com`. Then create a token for that user from admin.

### CODE REVIEW

**Comment by ragsagar** [comment]
Any update on this?

**Comment by shajith** [comment]
@ragsagar there are multiple ongoing efforts to verify/validate requests, we might need to allow for multiple reports about a request. Eg: how to handle conflicting reports, or status of a report changing?

**Comment by ragsagar** [comment]
If we are allowing multiple requests, at which stage the status of order will change?

**Comment by realslimshanky** [comment]
@ragsagar @shajith It's better to allow the person who created the request to close it as well.

**Pull request closed without merging**
