### PR TITLE
Rescue request API endpoint

### PR DESCRIPTION
**Pull request by hemanth7787**
Rescue request API endpoint with  token-authentication, pagination and filtering.

### CODE REVIEW

**Comment by nanospeck** [comment]
Hey hemant i like to use the API but how to token-authentication work? Where can i get a valid token once this is merged.

**Comment by hemanth7787** [comment]
@nanospeck  You can POST `username` and `password`  to `/api-token-auth/ ` to get a `token`
And pass the obtained token to Header as `Authorization: Token xxxxxxxx` for authenticating your requests

API permission is set to `IsAuthenticatedOrReadOnly` therefore GET requests don't need a token, only POST, UPDATE, PATCH and DELETE methods needs token.

i have also added a postman collection to the repo (under the `docs/api` folder),  so anybody can directly import the collection to thier postman application and test the api right away.

**Comment by hemanth7787** [comment]
http://www.django-rest-framework.org/api-guide/authentication/#tokenauthentication

**Comment by hemanth7787** [comment]
@irshadgit  I think somebody else is working on this and had some commits to `app` branch,   This PR is unlikely to be merged. 
https://github.com/IEEEKeralaSection/rescuekerala/issues/22

**Pull request closed without merging**
