### PR TITLE
Updated forms with bootstrap form-control

### LINKED ISSUE #643: Visual bugs for the search UI
Here are some visual bugs
- all the inputs must have a minimum height of 48px on mobile. Minimum apple touch guidelines says a touch area needs to be 44px or larger
- all inputs should be 100% width on mobile
- when you mix English and Malayalam it is unreadable, so have input labels be multiple.line one for each language. 
- That goes for all the text on the page
- Use html5 input types on all elements, for example for phone make it type=tel . See Mozilla mdn docs for other types https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/tel

### PR DESCRIPTION
**Pull request by thezillion**
### Issue Reference
This PR addresses the Issue : Fixes #643 

### Summarize
Updated all forms with bootstrap_form render, which adds the form-control and form-group classes to the forms. Pretty decent view on phone too.

> Added the bound_css_class=False because the 'has-success' class was being automatically added for some reason
screenshot from 2018-08-19 10-42-47
screenshot from 2018-08-19 10-42-59
screenshot from 2018-08-19 10-44-17

### CODE REVIEW

**Comment by r-tock** [comment]
@thezillion I have bulk of the visual changes here https://github.com/IEEEKeralaSection/rescuekerala/pull/662

**Comment by thezillion** [comment]
@r-tock I see that you fixed a lot of alignment issues. Awesome. But all forms would look better with the form-control class, right? Maybe we can merge both commits? @xaneem

screenshot from 2018-08-19 12-12-54

**Comment by r-tock** [comment]
Yes, both commits are complementary, would work great together.

**Comment by thezillion** [comment]
I have also added Selectize.js and added a new PR for that feature at #674. Please merge that if possible since it contains these commits as well.

**Pull request merged**
