### PR TITLE
Load request page with data

### PR DESCRIPTION
**Pull request by Projjol**
### Summarize

Currently the /request page loads with no data which can be confusing
to new users. This allows the page to always load with data and can be
modified as was earlier using the form

### CODE REVIEW

**Comment by vigneshhari** [comment]
You can just change the href in home page link to https://keralarescue.in/requests/?district= to achieve the same effect

**Comment by Projjol** [comment]
@vigneshhari thanks for taking a look, what you suggested is a much cleaner approach. thanks :)

**Comment by Projjol** [comment]
@vigneshhari I accidentally forgot to clean up importing QueryDict, should I squash these commits into one?

**Comment by vigneshhari** [comment]
I'll Squash and Merge

**Pull request merged**
