### PR TITLE
Add malayam names to district

### LINKED ISSUE #134: Translation : Malayalm of Districts (enhancement)
image

**Issue Description:**  Malayalam translation for the district names will be helpful.

Severity: Normal

Accepted behavior:  Show district names in Malayalam in bracket along with English names

Optional : Sorting based on the locations with highest issues could be helpful. Say Ekm, Wayand etc at the top.

### PR DESCRIPTION
**Pull request by littlestar642**
Fixes #134

### CODE REVIEW

**Comment by salmanulfarzy** [comment]
Duplicate of #136

**Comment by ABHISHEKVALSAN** [comment]
@ragsagar 
It would be better if districts are lexically ordered as advised by @naveenpf , people when seeing Alapuzha at the top will realize that is it ordered lexically. 
Else in a state of stress people have to search for their district.
Btw every district is critical.

**Comment by ragsagar** [comment]
@ABHISHEKVALSAN Makes sense

**Comment by biswaz** [comment]
Please rebase

**Comment by littlestar642** [comment]
@biswaz Done rebasing. Please review

**Comment by bobinson** [comment]
thanks  littlestar642 

@biswaz I hope we can deploy this and close on PR and issue

**Comment by biswaz** [comment]
#136 will do, you have removed necessary db fields

**Pull request closed without merging**
