### PR TITLE
Added alert in Share/Copy button in District Needs

### LINKED ISSUE #1098: Add an alert or a flash message saying "copied" in District wise requirements
Add an alert or a flash message saying "copied". The user doesn't understand what has happened after clicking the share/copy button from a desktop browser.

### PR DESCRIPTION
**Pull request by Gotham13121997**
### Issue Reference
This PR addresses the Issue : Fixes #1098 

### Summarize
Please, describe what the PR does, the changes you have made.

> Shows alert on Copy
> Copy only if share not available

### CODE REVIEW

**Comment by biswaz** [comment]
Alert should be subtle. The native alert button is not best thing considering UX. Could you please add something that doesn't obstruct user interaction and fades away in a while.

**Comment by Gotham13121997** [comment]
Sure

**Comment by Gotham13121997** [comment]
@biswaz As support for toast notification was added only in bootstrap 4. This is the best I can think of without using any other library or messing with css.

**Comment by biswaz** [comment]
LGTM.. please find testers from #testing

**Pull request merged**
