### PR TITLE
Add Id & Status on Registered Requests Page

### LINKED ISSUE #549: 'Request ID' & 'Status of Request' should be displayed in ‘Registered Requests’ Page
### Subject of the issue
'Request ID' & 'Status of Request' should be displayed in ‘Registered Requests’ Page .

"Request ID" column helps to identify, report & clean repeated/redundant issue details 
"Status" column (OPEN, INPROGRESS& CLOSED).) helps the public to address ‘OPEN’ issues . 
So please update ‘Registered Requests’ page with  ‘Request ID’ & ‘Status’

### Your environment
* version of your python:Python 3.7.0
* which browser and its version : Chrome 68.0.3440.106
* OS Type (iOS/Android/Linux/Windows): WINDOWS 10

### Steps to reproduce
1)	Enter following URL  Browser : https://keralarescue.in/

2)	Navigate to ‘Registered Requests’ Screen

3)	Display in contents with Necessary info of Registered Requests
https://keralarescue.in/requests/?district=

### Expected behaviour
Registered Requests’ Screen  will be displayed with  “request ID” & “Status” of request  along with “District”, “location” ,”Requestee”, “Phone” &”Date” . 

### Actual behaviour
“Registered  Requests” Screen has District, location ,Requestee, Phone & date . 
But it does not have unique “Request ID” & “Status” of request(OPEN, INPROGRESS& CLOSED).

#### More Details
Request ID helps to identify, report & clean repeated/redundant issue details 
Status helps the public to address ‘OPEN’ issues . 
So please update ‘Registered Requests’ page with  ‘Request ID’ & ‘Status’

### PR DESCRIPTION
**Pull request by darkdefender27**
### Issue Reference
This PR addresses the Issue : Fixes #549 

### Summarize
Add Id & Status on Registered Requests Page 
- Add status as filter 
- Modified pagination links to include status filter

### CODE REVIEW

**Comment by malgamves** [comment]
Testing!

**Comment by renjithraj2005** [comment]
@darkdefender27 please resolve the conflicts

**Comment by darkdefender27** [comment]
@renjithraj2005 Done.

**Comment by darkdefender27** [comment]
@renjithraj2005 If you have write access, can you please merge this in?

**Pull request closed without merging**
