### PR TITLE
Use Pipenv instead of requirements.txt and virtualenv setup

### PR DESCRIPTION
**Pull request by darkdefender27**
### Issue Reference
This PR addresses the Issue : Fixes # *NA*

### Summarize
1. Replace requirements.txt with pipenv setup (Pipfile and Pipfile.lock)
2. Updated README with installation instructions with pipenv.

#### key points if any to look into while code reviews
1. Please check if all deps are installed with the new setup process and you are able to launch a virtualenv using `pipenv shell` command.

### CODE REVIEW

**Comment by jilvin** [comment]
@darkdefender27 Duplicates #23. Please contribute to #23. Else clarify.

**Comment by darkdefender27** [comment]
@jilvin #23 suggests usage of virtualenv which will still require you to pre-emptively create and activate the virtualenv. With Pipenv you need not worry about it. Just a Pipfile is sufficient to get you started. 
You'll just have to clone the repo and run `pipenv install && pipenv shell`; This will install a venv and install all the deps in the venv and activate it for you.

**Comment by jilvin** [comment]
@darkdefender27 Can you check out #392.

**Comment by darkdefender27** [comment]
@jilvin Awesome. he's already put in the changes. Only a merge is pending it seems. Should I close this particular PR?

**Comment by jilvin** [comment]
@darkdefender27 Yes please close the pr. If possible please review and test #392. Cheers.

**Comment by darkdefender27** [comment]
#392

**Comment by darkdefender27** [comment]
@jilvin I also plan to add Makefile for automating some more stuff. 
@arocks Can you please add travis changes to your original PR, please?

**Comment by jilvin** [comment]
@darkdefender27 Its better if you and @arocks can make a combined pr rather than two separate prs. I have talked with @vigneshhari. He will look into this matter after the core issues have been tackled.

**Pull request closed without merging**
