### PR TITLE
Added place picker and fixed minor bugs

### LINKED ISSUE #248: Requesting for others still sends GPS coords of user
### Subject of the issue
Selecting requesting for others still sends the current users GPS coordinates to the server

### Steps to reproduce
Goto /requests and select requesting for others. Fill other details and send. 

### Expected behaviour
Should not send any gps coordinates

### Actual behaviour
DB will have the gps coordinate of the current user

### PR DESCRIPTION
**Pull request by msrshahrukh100**
### Issue Reference
This PR addresses the Issue : Fixes #248 #225 

## Changes
+ Added a placepicker which is shown when the auto location fetch part fails with an error
+ Or when the user wants to enter manually
+ Requesting for others doesn't enter the current location and empties the field
+ Now on closing the instructionModal calls the gps location fetching part, rather than only when the user clicks the button

+ **Disclaimer**: the gps accuracy is set to "0 Meters", reason for this is google auto complete api doesn't seem to provide the accuracy. Also the user is entering the location manually.

### CODE REVIEW

**Comment by msrshahrukh100** [comment]
it uses, google places api, which is free for first 10k or so requests, and for the rest i'll manage

**Comment by irshadshalu** [comment]
Can someone get a Google API key with billing enabled?. (I think I saw a comment saying someone having a 3000$ Google credit.)

**Comment by answerquest** [comment]
@msrshahrukh100 how about we pool to make a list of google API keys, and the site uses a different one every minute?

**Comment by msrshahrukh100** [comment]
yea we can do that, or else if someone has some google credits than we can use his key, or else the cost may not be that high, moreover for most users the browser navigator should work fine,

**Comment by sumodm** [comment]
I am testing this

**Comment by biswaz** [comment]
Urgently needs to deploy this. Rescue team cant use inaccurate gps locations

**Comment by vrthra** [comment]
@biswaz checking it now.

**Comment by vrthra** [comment]
@msrshahrukh100 could you please join the slack channel #testing (see readme for info)? Could you please respond to @sumodm? it seems the location is not poping up. Could you explain the expected behavior?

**Comment by msrshahrukh100** [comment]
ok I am coming on slack

**Comment by namboodiri** [comment]
Shouldn't clicking on "Requesting for others" checkbox show this ('Enter location manually') input field automatically?

**Comment by namboodiri** [comment]
BUG : Place search not working when "Requesting for others" is checked.

**Comment by sumodm** [comment]
@msrshahrukh100 Tested the same. 

@biswaz @vrthra The functionality is that when the user doesn't enter GPS coords, the location field is enabled which is queries against Google Maps. So instead of the location text field, we get real locations which can then be fed to maps.

1. Added a placepicker which is shown when the auto location fetch part fails with an error
2. Or when the user wants to enter manually
3. Requesting for others doesn't enter the current location and empties the field
4. Now on closing the instructionModal calls the gps location fetching part, rather than only when the user clicks the button

1, 2 working :+1: 
3: Do we need to handle the case where people want to enter specific details like GPS coord etc that they have of other people. @biswaz @vrthra @msrshahrukh100

**Comment by msrshahrukh100** [comment]
well for case 3, its because there was some issue where the location of the one making a request on behalf of someone else was recorded. So I emptied the field and displayed the manual location input box. 
Also the lat lang field is set as blank=True, in models so a user will be able to submit the form.

**Comment by sumodm** [comment]
@msrshahrukh100 Also do we need one of location field at the top (we end up having two redundant location fields). May be we can make the first location (location details) and your one, the location (coarser) since this API you are using might not provide very granular details

**Comment by msrshahrukh100** [comment]
oh yes, i get your point, in that case we can just use the same old location field and display a drop down there

**Comment by sumodm** [comment]
@msrshahrukh100 It seems a little flaky also. Initially, I thought I might have done some mistake but doesn't seem to work all the time. Will update you when exactly it is not working.

**Comment by msrshahrukh100** [comment]
so what do you suggest, we should rename the fields or what?

**Comment by msrshahrukh100** [comment]
oh ok sure

**Comment by biswaz** [comment]
@vrthra Your merge caused the recent 500 error. Please don't merge. Use your permissions only for issue tracking

**Comment by jithinanchanattu** [comment]
Good work.

**Comment by answerquest** [comment]
Hi, is this in or out or still under testing or ? There's 2 PR's for location picker, nothing up on site yet.

**Comment by msrshahrukh100** [comment]
It's there on site

**Comment by codelust** [comment]
Is the Google Location API credits still required for this?

**Comment by msrshahrukh100** [comment]
no I have already added one

**Comment by riginoommen** [comment]
@codelust Yes actually

**Comment by riginoommen** [comment]
@codelust but there is a free tier is their

**Comment by msrshahrukh100** [comment]
No it's not a free tier one

**Comment by lijoantony** [comment]
Is this on production? I found that the GPS location is missing (shown as NA) for requests created for others

**Pull request merged**
