### PR TITLE
Add perma_link for UPI payment

### PR DESCRIPTION
**Pull request by SpEcHiDe**
create a permanent link for UPI payments, for mobile first users.

### CODE REVIEW

**Comment by sanpra1989** [comment]
@SpEcHiDe Could you please make it a separate line? A little hard to tell that there are two links there.

**Comment by sanpra1989** [comment]
Seems to duplicate #36

**Comment by SpEcHiDe** [comment]
@sanpra1989 Sorry. But I do not have much experience in CSS, or styling.

**Comment by josethomasd** [comment]
Looks like adding a new line using <br> will be enough.

**Comment by josethomasd** [comment]
Looks like adding a new line using `<br>` will be enough.

**Comment by jilvin** [comment]
@SpEcHiDe Can you make the script part better?

**Comment by jilvin** [comment]
Please checkout #510.

**Comment by remedcu** [comment]
Related PR's & Issues : #36 #52 #90 #141 #350 #402 #468 #510 #614 

Quoting @biswaz 

"Officials want just a link to the official portal. Sorry KSITM requirements are our first priority. I know exactly what it feels like be on the contributor side. Been there, done that."

So, I believe this can be closed.

@syam3526 @vigneshhari @vrthra @bobinson

**Pull request closed without merging**
