### PR TITLE
Fix sql query duplication

### LINKED ISSUE #519: Sql query duplication
### Subject of the issue
Sql queries are being duplicated to fetch `RescueCamp` query set and to set the initial one.

### Your environment
* Python3.6
* Firefox 62.0
* MacOS

### Expected behaviour
The `initial` value of `camped_at` can be derived from the already fetched query set.

### Actual behaviour
Two sql queries are fired.

### PR DESCRIPTION
**Pull request by mjzac**
Rescue camp query set is already being fetched. No second query to the db is required to get the initial entry.

### Issue Reference
This PR addresses the Issue : Fixes #519 

### Summarize
Fetched a single queryset. Used the first entry to be used as initial value of `camped_at`

### CODE REVIEW

**Comment by sarath263** [comment]
@mjzac Can u resolve conflicts..

**Comment by mjzac** [comment]
@sarath263 yep. Fixed those.

**Comment by code-haven** [comment]
Querysets in Django are Lazy.  I don't see how this change would result in fewer queries. 
https://docs.djangoproject.com/en/2.1/topics/db/queries/#querysets-are-lazy

**Comment by mjzac** [comment]
@code-haven Here the db call results are being stored into two different variables. Thus the need to reuse result from first db call. Else even if the queryset is lazy, two calls will be triggered.

**Pull request merged**
