### PR TITLE
Update request_list.html

### PR DESCRIPTION
**Pull request by JijinJayakumar**
added data table

### CODE REVIEW

**Comment by JijinJayakumar** [comment]
@kira0204  someone added Django-filter to it  , and we added client-side pagination , please disable one

**Comment by sideffect0** [comment]
@JijinJayakumar @kira0204  The changes should consider different client types like low end mobile phones, bandwidth etc. means do not try to include any heavy load JS libs, any client side rendering techniques

**Comment by sadu** [comment]
This PR is fragmented with #8 #9 #11 and #12 please reconsider merging changes in this pattern

**Comment by JijinJayakumar** [comment]
as we added server-side I think we can  close this :)

**Pull request closed without merging**
