### PR TITLE
Make home buttons smaller

### LINKED ISSUE #511: Make home buttons smaller to accommodate buttons in two rows (in bigger screens)
### Subject of the issue
Describe your issue here.

### Your environment
* version of your python
* which browser and its version
* OS Type (iOS/Android/Linux/Windows)

### Steps to reproduce
Tell us how to reproduce this issue. Please provide a working demo as a GIF, if possible.

### Expected behaviour
Tell us what and how exactly is it supposed to  happen

### Actual behaviour
Tell us what happens instead or what went wrong

### PR DESCRIPTION
**Pull request by shubhamgoyal42**
Decrease width from 230 px to 208 px. Now it shows 2 rows of buttons instead on 3.

### Issue Reference
Fixes #511

> Also, mention the key points if any to look into while code reviews

### CODE REVIEW

**Comment by shubhamgoyal42** [comment]
changed_homepage

**Comment by shubhamgoyal42** [comment]
@malgamves - changed to %. Can you please check if it works now?

**Comment by malgamves** [comment]
Your test failed. Make sure you're upto date on your branch with the master.

**Comment by shubhamgoyal42** [comment]
I don't understand. @malgamves - can you help me understand why this is failing?
Going through the stack trace, it looks like Postgres is throwing Syntax error. Is the postgres version correct in the travis config?

**Pull request closed without merging**
