### PR TITLE
Modified requests list view and request details view, fixes mobile issues

### LINKED ISSUE #132: scroll issue in  request details page
Steps to reproduce
----------------------------

1)Open the page https://keralarescue.in/requests/.

2) Select a district and click the submit button.

Actual behavior
---------------------
Listed data in a table but the horizontal scroll is not visible

Expected
-------------------
Should list the data with proper scroll

### PR DESCRIPTION
**Pull request by gauthams09**
### Issue Reference
fixes #132 #147 

### Summarize
1. Modified requests list view to have stacked view on mobile (screens less than 800px)
2. Reduced columns in requests list view and added detailed view for more information regarding specific request.
> Pls check specifically from smartphone during testing

### CODE REVIEW

**Comment by jithu1990** [comment]
im starting to test this fix

**Comment by jose2007kj** [comment]
listview working fine in mobile device

**Comment by jose2007kj** [comment]
whatsapp image 2018-08-17 at 1 34 50 am

**Comment by jose2007kj** [comment]
Tested in mobile device and its working fine

**Comment by biswaz** [comment]
Fix conflict

**Pull request merged**
