### PR TITLE
Removed unwanted call to google font

### LINKED ISSUE #220: Remove unwanted call to the font
We're calling to the Monteserrat font on this https://github.com/IEEEKeralaSection/rescuekerala/blob/master/templates/base.html#L74 line. remove it since it affects performance.

### PR DESCRIPTION
**Pull request by PSNAppz**
### Issue Reference
This PR addresses the Issue : Fixes #220 

### Summarize
Removes the unwanted call of font.

### CODE REVIEW

**Comment by sreecodeslayer** [comment]
Duplicate of #222 : Consider merging one and closing both

**Comment by aashiks** [comment]
Tested okay.

**Comment by asimqt** [comment]
Duplicate of https://github.com/IEEEKeralaSection/rescuekerala/pull/222

**Comment by MansoorMajeed** [comment]
I think we should close this in favour of #222

**Pull request closed without merging**
