### PR TITLE
Update views.py - filter system according to type of need

### LINKED ISSUE #305: Implement a filter system according to type of need.
**Expected behaviour**

Help requests can be filtered by the needs/ or combination of needs 

Check the image below... Something like this will be helpful...
Thank you.

artboard

### PR DESCRIPTION
**Pull request by sreevenkat**
### Issue Reference
This PR addresses the Issue : Fixes #305 

### Summarize
Please, describe what the PR does, the changes you have made.

Add the following boolean fields as filterable checkboxes:
- Need Rescue
- Water
- Food
- Clothing
- Medicine
- Kitchen utensil
- Toiletries.
 
Choosing the filters based on the checkboxes in the form at https://www.keralarescue.in/request/

screen shot 2018-08-17 at 5 54 16 pm

> Also, mention the key points if any to look into while code reviews

For review look at views.py function `filter_by_needs_filter`

### CODE REVIEW

**Comment by ajaykanayil** [comment]
Try list-style: none in css styles...

**Comment by sreevenkat** [comment]
Thanks for sharing that. It works. Pushed it.

**Comment by sreevenkat** [comment]
It says all checks have passed. Should i close this pull request now ?

**Comment by sreevenkat** [comment]
@lifeeth @vrthra @shajith are you guys managing feature merges ?

**Pull request closed without merging**
