### PR TITLE
removed font railway

### PR DESCRIPTION
**Pull request by visakhsuku**
based on issue #85 and changed to standard web font.

### CODE REVIEW

**Comment by ladderlogician** [comment]
Isn't font loading should also be removed?

**Comment by visakhsuku** [comment]
it wouldn't be loaded if it isn't referenced right?

**Comment by ladderlogician** [comment]
No,I checked in chrome.

**Comment by ladderlogician** [comment]
Yes , It is working

**Comment by bodhish** [comment]
Tested. #105 has to be merged with 95

**Pull request merged**
