### PR TITLE
Fixed bugs & Implemented new modal PlacePicker for /requests/ page.

### LINKED ISSUE #125: URGENT fix needed - unable edit location info
**SEVERITY : HIGHEST SEVERITY AND PRIORITY**

**Issue:** Unable to manually edit the location information. I was trying to enter information of someone's parents and not able to edit.

Environment: Firefox on mac os  and Chrome : both tested on macos.

image

image

Steps to reproduce:

**scenario 1:**

1. Allow browser to Access GPU location
2. The location details are auto filled

3. Unable to edit to the location

This is the case in Chrome and FF

**Scenario2:** 

1. Don't allow browser to access location
2. The location details are hidden

image

PS: Power went out and I will not be to confirm.

### PR DESCRIPTION
**Pull request by irshadshalu**
### Issue Reference
This PR addresses the Issue : Fixes #125 #225  #628 #624 

### Summarize
Implements a Modal placepicker with better workflow as originally preferred. The user can drag and place or enter a valid GPS coordinate manually even when requesting for others. Fixed all other bugs and confusions as well

- Hiding the accuracy field as it will only confuse those who request.
- Hiding help label which said _If it is enabled, no need to consider lat and lng_
- Removing old placepicker which had bugs.

Screenshot
screen shot 2018-08-19 at 2 32 57 pm

Changes are only made in a single file so that it won't be hard to merge and no rebase/migration will be needed.

### CODE REVIEW

**Comment by irshadshalu** [comment]
Did it @riginoommen

**Comment by salmanulfarzy** [comment]
Modal is confusing and difficult to navigate on mobile UI.

**Comment by salmanulfarzy** [comment]
Place picker modal is confusing and difficult to navigate on mobile UI. Looks good on desktop.

**Comment by irshadshalu** [comment]
@salmanulfarzy  Can you suggest a solution to this?

**Comment by irshadshalu** [comment]
I'm closing this after squashing in #695

**Pull request closed without merging**
