### PR TITLE
Added endpoint for priority check 

### PR DESCRIPTION
**Pull request by adamshamsudeen**

### CODE REVIEW

**Comment by adamshamsudeen** [comment]
Please merge it!

**Comment by sanpra1989** [comment]
The intention is to simply make data available for other tools to perform urgency check? I'd recommend remove details such as phone numbers.

**Comment by gladiatorvarg** [comment]
Testing

**Comment by gladiatorvarg** [comment]
I can confirm this works. But I am concerned on the load this API will put on the system since millions of rows will be downloaded in JSON format. I suggest further improvements to API by enabling pagination.

**Comment by adamshamsudeen** [comment]
@sanpra1989 the api is to generate csv based on priority, so we need the phone number.

**Comment by sanpra1989** [comment]
@gladiatorvarg Apparently, this is going to be a one-off use, once the data is extracted, the API is to be closed again. @adamshamsudeen Please confirm.

**Comment by adamshamsudeen** [comment]
Yes, once the data is extracted we can revoke this API.

**Comment by ranjithn** [comment]
Tested this works.

But I echo @gladiatorvarg 's concern.

Why do we need this? Admin page has the ability to fetch csv data anyway.

**Comment by adamshamsudeen** [comment]
Please go through this:  https://github.com/adamshamsudeen/Kerala-flood-priority
we need a dump to run this script.

**Comment by kurianbenoy** [comment]
This API works a @adamshamsudeen . Were are you planning to [run this script](https://github.com/adamshamsudeen/Kerala-flood-priority)?

**Comment by gvmani** [comment]
@kurianbenoy  @adamshamsudeen  Why don't we dump data to AWS S3 or similar maybe every 5 mins. Others apps can use data from there rather than hitting the server directly.

**Comment by midhunkrishna** [comment]
Dumping the entire data through the ORM is going to slow down the server as well as the db. +1 for a periodic backup

**Comment by vigneshhari** [comment]
We have a similar API, but we have shut it down because of DB Usage.

**Comment by adamshamsudeen** [comment]
@vigneshhari  Is there a way to access the data? or may be a dump?

**Comment by gvmani** [comment]
@vigneshhari @adamshamsudeen  as per #322 there are db issues due to this api usage. Check with @bobinson

**Comment by vigneshhari** [comment]
Yeah those are being addressed now, Please minimize the use of the API for the Database to Remain Steady

**Comment by biswaz** [comment]
@naveenpf This won't satisfy https://github.com/IEEEKeralaSection/rescuekerala/issues/275
This just returns json data. You need scv

**Comment by biswaz** [comment]
This will cause too much load of the db

**Pull request closed without merging**
