### PR TITLE
Resolving Issue - Link not clickable

### LINKED ISSUE #774: Link not clickable
### Unable to click link
The links in https://keralarescue.in/district_needs are not not clickable

### Steps to reproduce
1. Go to https://keralarescue.in/district_needs
2. Notice there are three columns namely 'District', 'Items required' and 'Contacts & Collection points'
3. In the column 'Contacts & Collection points' google map address links are included
4. Hover the mouse over those links

### Expected behaviour
The links should be highlighted automatically

### Actual behaviour
It does not highlate. It is plain text.

### PR DESCRIPTION
**Pull request by ladvine**
### Issue Reference
This PR addresses the Issue : Fixes #774 

### Summarize
Used urlize to automatically detect and convert markups.

### CODE REVIEW

**Comment by ladvine** [comment]
Please review and merge the branch

**Comment by jojurajan** [comment]
The model names have been updated in master. Please check your conflict resolution and update as required.

**Comment by bobinson** [comment]
@ ladvine  - please update the PR

**Comment by ladvine** [comment]
@jojurajan @bobinson @vikaskyadav 
Please review and approve pull request.
#780 should be fixed.

**Comment by ladvine** [comment]
Added resolution for #873 also.

**Pull request closed without merging**
