### PR TITLE
Add donations bank account details and UPI QR codes

### LINKED ISSUE #402: QR code to display in https://keralarescue.in/reg_contrib/
### Subject of the issue
CM relief fund redirection (https://donation.cmdrf.kerala.gov.in/) loading too slow and hence recommended to display the QR codes directly in this page,  https://keralarescue.in/reg_contrib/ for easy transfer

### PR DESCRIPTION
**Pull request by arjunkomath**
### Issue Reference
This PR addresses the Issue : Fixes #402 

### Summarize
- Added all bank account details and QR codes
- Please cross verify bank account information for accuracy. Double check the data!

Screenshot of changes:
donations-info

### CODE REVIEW

**Comment by aravindharinair** [comment]
Verified bank account details.

**Comment by DextersHub** [comment]
Double checked bank details.

**Federal Bank**: _Status Change_ 
**Temporarily Out of Service due to floods**

**New bank added:**
HDFC
PAYMENT GATEWAY SERVICES 
Internet Banking - 53 banks supported
Domestic Credit and Debit Cards supported
INTERNATIONAL Credit & Debit Cards supported	
payment charges: Nil
ACCOUNT DETAILS 
A/c Number : 50100248534439
A/c Name: Chief Minister’s Distress Relief Fund
Branch: Vattiyoorkavu, Trivandrum 
IFSC : HDFC0002485
SWIFT CODE: HDFCINBBXXX

**Comment by aravindharinair** [comment]
@DextersHub are you sure about Federal Bank outage?
I've got a contact there. Will confirm and report back once bank opens at 10.

**Comment by DextersHub** [comment]
@aravindharinair It's updated on https://donation.cmdrf.kerala.gov.in/ website

**Comment by aravindharinair** [comment]
@DextersHub Reflected changes here #510 
Do verify & test.

**Comment by jilvin** [comment]
Close this and contribute to #510.

**Comment by arjunkomath** [comment]
Closed in favour of #510

**Pull request closed without merging**
