### PR TITLE
Added place search autocomplete field in request_form, Refactored code.

### PR DESCRIPTION
**Pull request by irshadshalu**
### Issue Reference
This PR is an enhancement over #695 as recommended by @biswaz . It also solves #225 #249 #471 , etc.

### Summarize

* Added places autocomplete API for easily searching for a place. 
* Refactored the code and fixed indentation inconsistency, etc..

Possible enhancements:

> Move script and style logic to separate files.
> Add provision for internationalization

### CODE REVIEW

**Comment by irshadshalu** [comment]
Seems like only cities are appearing in search results. will fix it!

**Comment by bobinson** [comment]
@irshadshalu - hows it going :-)

**Comment by biswaz** [comment]
Testing at test.keralarescue.in

**Comment by bobinson** [comment]
ok

**Pull request merged**
