### PR TITLE
Add permalinks for announcements

### LINKED ISSUE #1017: Give More Exposure to Announcements
### Subject of the issue
The "Announcement section" in the Home page  needs to be given more exposure. 
Rather than listing it among the other sections in the Home page, would be better if displayed on top of the page as a badge or using some highlighter.
And within the Announcement page , the each  announcement listing could be given a heading ,or use some hashtags on top (for eg: #Ernakulam #relief camps, etc) ,add  social media  share buttons for easy sharing of messages. The priority levels (coloring code) marked could also be improved , cant figure out it for a layman user. Right now, its hardly noticeable.

### PR DESCRIPTION
**Pull request by subins2000**
### Issue Reference
This PR addresses the Issue : Fixes #1017 

### Summarize
Add permalinks for announcements

Sample URL : https://keralarescue.in/announcements/2 https://keralarescue.in/announcements/4

### CODE REVIEW

**Comment by sreenadh** [comment]
Why not a separate view file like announcement-view.html or announcements/view.html ?

**Comment by subins2000** [comment]
@sreenadh Because it's easier to manage the announcemen cardt view in one page itself.

There's an additional proposal to add sharing buttons too.

**Comment by sreenadh** [comment]
Share buttons can be put in separate view file and include both in both views. In future we might need more feature separately for view and announcements then announcements.html will get bloated with if else conditions.

**Comment by subins2000** [comment]
@sreenadh you're right. This was just a quick hack. In case there is more differences between the two, it should be separated.

**Comment by tomahawk-pilot** [comment]
fix the conflicts please

**Comment by subins2000** [comment]
@tomahawk-pilot done

**Pull request merged**
