### PR TITLE
Urlize the links in announcements

### PR DESCRIPTION
**Pull request by subins2000**
### Summarize
Make link text in announcements clickable. 

I haven't tested the code. This is a simple addition. Haven't setup the local env yet, otherwise I would have tested it out myself. Please test if this works and then only merge.

### CODE REVIEW

**Comment by tomahawk-pilot** [comment]
@riginoommen is it tested??

**Comment by riginoommen** [comment]
@tomahawk-pilot Not tested but Urlize is a small change thats why i merged

**Comment by subins2000** [comment]
Does every merge gets automatically deployed to the server ?

**Comment by subins2000** [comment]
@tomahawk-pilot I just setup my local env and tested. It works

**Pull request merged**
