### PR TITLE
Update for relief camps page

### PR DESCRIPTION
**Pull request by xaneem**
### Summarize
Updates several things in the relief camps page:
- Contact numbers are clickable links, supports multiple lines
- Added map link for relief camps
- Relief camps grouped by district
- Updated UI for add person

Please test thoroughly.

### CODE REVIEW

**Comment by sumodm** [comment]
Testing: Creating mock data, since no mock data available.

**Comment by sumodm** [comment]
Coordinator login on successful login takes you to the add_person screen. Here there is no option in  'camp' dropdown. Don't know how important this is

screenshot from 2018-08-17 13-38-33

**Comment by sumodm** [comment]
Basic functionality seems works, doing some stress testing @xaneem

**Comment by xaneem** [comment]
Guys,

District is for the address of the person (not camps district).

To get camps to populate, link a user to the camp from Django admin.

**Comment by jose2007kj** [comment]
whatsapp image 2018-08-17 at 2 21 49 pm

**Comment by jose2007kj** [comment]
whatsapp image 2018-08-17 at 2 30 42 pm
Pearson page working fine....... do we need to add validation in address field and phone number filed while adding person also  shall we make the table responsive in mobile devices(not important)

**Comment by xaneem** [comment]
@jose2007kj Thanks. Validation might be cumbersome for people entering data. Keeping it simple for now.

@biswaz Can we merge this?

**Pull request merged**
